### ISSUE TITLE
程式無法執行

### ISSUE THREAD

**Issue by mimijgt** [k66inthesky/TW-stock#1]
python 剛接觸原本想看網站自學，只是不曉得何年才會寫好；想不到連直接用妳寫好的程式也困難重重；在anacoda環境中 的VS code 執行。
麻煩妳看一下該如何解決,謝謝!
附上截圖
![錯誤訊息](https://github.com/user-attachments/assets/e089a1fb-8f32-4683-b655-78a5ca2d31a7)

**Comment by k66inthesky** [comment]
@mimijgt 報錯最後一行有寫，看起來是你在跑起來前沒建立一個新資料夾叫stocks(YT影片有說明)
希望有幫助到你~

**Comment by k66inthesky** [comment]
@mimijgt 我看你有給我按表情了，所以我先關這條issue囉~
如果還遇到什麼其他問題，可以再開其他條issue

**Comment by mimijgt** [comment]
> @mimijgt 報錯最後一行有寫，看起來是你在跑起來前沒建立一個新資料夾叫stocks(YT影片有說明) 希望有幫助到你~

> 哈!看到一堆訊息，原來只須注意最後一行!可以執行了!
我再研究一下，如果有不懂或做不出來的再請教妳。
感謝!
請妳喝杯咖啡!
